# -*- coding: utf-8 -*-
"""scale-tile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rBrDfYWhJaF4GgDJa182Z3inhtExaJYp
"""

# Commented out IPython magic to ensure Python compatibility.
# from google.colab import drive
# drive.mount('/content/drive')
# !pwd
# %cd /content/drive/MyDrive/Tile/

from matplotlib import image
import numpy as np
from PIL import Image
import PIL
import keras
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import glob
from copy import deepcopy as dc
size_select_w = 128
size_select_h = 128
codes=[1345,1356,1389,1395,1407,1479,1762,1766,1783,1826]

for class_write, class_kashi in enumerate(codes):
    path_img = [cv2.imread(file) for file in glob.glob(fr"C:\Users\ali\PycharmProjects\ACGAN-Kashi\images\C-{class_kashi}*.jpg")]
    print(path_img)
    print(1)
    for k in range(len(path_img)):

        height = path_img[k].shape[1]
        width = path_img[k].shape[0]
        batch_w = int(np.floor(width / size_select_w))
        batch_h = int(np.floor(height / size_select_h))
        # plt.imshow(path_img[0])
        # plt.show()
        subimg = []
        image_number=0
        for i in range(1, batch_w):
            for j in range(1, batch_h):
                image_number += 1
                img_crop = path_img[k][(i - 1) * size_select_w: (i) * size_select_w,
                           (j - 1) * size_select_h: (j) * size_select_h]

                if (img_crop.shape[0] == size_select_w and img_crop.shape[1] == size_select_h):
                    # plt.imshow(img_crop)
                    # plt.show()
                    filename0 = fr"C:\Users\ali\PycharmProjects\ACGAN-Kashi\saved\{class_write}_{k}_{image_number}.jpg"
                    im1 = Image.fromarray(img_crop)
                    im1 = im1.save(filename0)
                    # print(s)
